version : "3.7"
services :
  proyectos-monolitica :
    container_name : proyectos-monolitica
    image : proyectos-monolitica:v1
    build :
      context: .
    ports : 
      - "4001:4001"
    networks :
      - proyectos-app

  proyectos-monolitica-2 :
    container_name : proyectos-monolitica-2
    image : proyectos-monolitica:v1
    build :
      context: .
    ports : 
      - "4001"
    networks :
      - proyectos-app

  proyectos-monolitica-3:
    container_name : proyectos-monolitica-3
    image : proyectos-monolitica:v1
    build :
      context: .
    ports : 
      - "4001"
    networks :
      - proyectos-app

  proyectos-monolitica-4 :
    container_name : proyectos-monolitica-4
    image : proyectos-monolitica:v1
    build :
      context: .
    ports : 
      - "4001"
    networks :
      - proyectos-app 

networks :
  proyectos-app :